spring.application.name=gestionstock
server.port=8080

# Perfil por defecto (local)
spring.profiles.active=local

# Seguridad
spring.security.oauth2.resourceserver.jwt.secret-key=mysupersecretkeymysupersecretkey

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/docs
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.tryItOutEnabled=true

springdoc.group-configs[0].group=airtable
springdoc.group-configs[0].display-name=Airtable API
springdoc.group-configs[0].paths-to-match=/api/airtable/**

springdoc.group-configs[1].group=gestionstock
springdoc.group-configs[1].display-name=GestionStock API
springdoc.group-configs[1].paths-to-exclude=/api/airtable/**

# Airtable
airtable.api.base-url=https://api.airtable.com/v0
airtable.api.token=${AIRTABLE_PAT_TOKEN:pat_default}
airtable.api.base-id=appySkBtaOnlmgv2o
airtable.api.table-id=tbliYJUIePWGerQZn